"use client";

import { useEffect } from "react";
import { Printer } from "lucide-react";
import type { PlanItinerary, PlanBlock } from "@/lib/planner/types";

interface Props {
  title:      string;
  cityLabel:  string;
  duration:   number;
  guideLabel: string | null;
  itinerary:  PlanItinerary;
  locale:     string;
}

/* ─── Time formatter ─────────────────────────────────────────────────────────── */

function fmt(t: string | undefined) {
  if (!t) return "";
  const [h, m] = t.split(":").map(Number);
  const period = h >= 12 ? "PM" : "AM";
  return `${h % 12 || 12}:${String(m).padStart(2, "0")} ${period}`;
}

/* ─── Block row ─────────────────────────────────────────────────────────────── */

function BlockRow({ block }: { block: PlanBlock }) {
  const timeStr = block.time
    ? `${fmt(block.time.start)}${block.time.end ? ` – ${fmt(block.time.end)}` : ""}`
    : "";

  const isNote     = block.item.type === "NOTE";
  const isLogistic = !!block.logisticsType;

  return (
    <tr className="border-b border-gray-100 last:border-0 print:break-inside-avoid">
      <td className="py-2 pr-4 w-28 text-xs text-gray-400 whitespace-nowrap align-top pt-3 font-mono">
        {timeStr}
      </td>
      <td className="py-2 pr-3 w-5 align-top pt-3.5">
        <span className={`inline-block h-2 w-2 rounded-full ${
          isNote     ? "bg-amber-400" :
          isLogistic ? "bg-blue-400"  :
                       "bg-primary"
        }`} />
      </td>
      <td className="py-2 align-top">
        <p className={`text-sm font-semibold leading-snug ${isNote ? "text-amber-700" : "text-gray-900"}`}>
          {block.customTitle ?? block.item.name}
        </p>
        {block.item.location && (
          <p className="text-xs text-gray-400 mt-0.5">{block.item.location}</p>
        )}
        {block.guideNote && (
          <p className="text-xs text-gray-500 mt-1 italic leading-relaxed">{block.guideNote}</p>
        )}
        {block.item.price > 0 && (
          <p className="text-xs text-gray-400 mt-0.5">
            TND {block.item.price}
            {block.item.priceLabel ? ` / ${block.item.priceLabel}` : ""}
          </p>
        )}
      </td>
    </tr>
  );
}

/* ─── Print view ─────────────────────────────────────────────────────────────── */

export function PrintView({ title, cityLabel, duration, guideLabel, itinerary, locale }: Props) {
  useEffect(() => {
    document.title = `${title} — Guidni`;
  }, [title]);

  return (
    <>
      {/* Global print styles */}
      <style>{`
        @media print {
          /* Hide everything except the print-area */
          body > *:not(#print-root) { display: none !important; }
          #print-root { display: block !important; }
          .no-print { display: none !important; }
          @page { margin: 18mm 14mm; }
          body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
        }
      `}</style>

      {/* Print-only root — hidden in normal view, shown when printing */}
      <div
        id="print-root"
        className="hidden print:block font-sans text-gray-900 bg-white"
        style={{ fontFamily: "system-ui, sans-serif" }}
      >
        <header className="mb-8 pb-4 border-b-2 border-primary">
          <h1 className="text-2xl font-bold text-gray-900 mb-1">{title}</h1>
          <p className="text-xs text-gray-500 flex gap-3">
            {cityLabel && <span>{cityLabel}</span>}
            <span>{duration} {duration === 1 ? "day" : "days"}</span>
            {guideLabel && <span>By {guideLabel}</span>}
          </p>
        </header>

        {itinerary.days.map((day) => (
          <section key={day.dayNumber} className="mb-8 break-inside-avoid">
            <div className="flex items-baseline gap-3 mb-3">
              <span className="text-xs font-bold text-primary uppercase tracking-widest">Day {day.dayNumber}</span>
              {day.theme && <span className="text-base font-bold text-gray-900">{day.theme}</span>}
            </div>

            {day.notes && (
              <p className="text-xs text-gray-600 mb-3 px-3 py-2 bg-amber-50 border-l-2 border-amber-400 rounded-sm leading-relaxed">
                {day.notes}
              </p>
            )}

            <table className="w-full border-collapse">
              <tbody>
                {day.blocks.map((block) => (
                  <BlockRow key={block.id} block={block} />
                ))}
              </tbody>
            </table>
          </section>
        ))}

        <footer className="mt-10 pt-4 border-t border-gray-200 flex justify-between text-xs text-gray-400">
          <span>Generated by Guidni</span>
          <span>guidni.com · {new Date().toLocaleDateString(locale)}</span>
        </footer>
      </div>

      {/* ── Screen preview (visible in browser, hidden when printing) ── */}
      <div className="no-print min-h-screen bg-gray-50">
        <div className="max-w-2xl mx-auto px-4 py-12">

          {/* Action bar */}
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{title}</h1>
              <p className="text-sm text-gray-500 mt-0.5">
                {cityLabel && <span>{cityLabel} · </span>}
                {duration} {duration === 1 ? "day" : "days"}
                {guideLabel && <span> · {guideLabel}</span>}
              </p>
            </div>
            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 px-5 py-2.5 bg-primary text-white text-sm font-semibold rounded-xl hover:bg-primary/90 transition-colors"
            >
              <Printer className="h-4 w-4" />
              Print / Save PDF
            </button>
          </div>

          {/* Days */}
          {itinerary.days.map((day) => (
            <section
              key={day.dayNumber}
              className="mb-6 bg-white border border-gray-100 rounded-2xl p-6"
            >
              <div className="flex items-baseline gap-3 mb-4">
                <span className="text-xs font-bold text-primary uppercase tracking-widest">Day {day.dayNumber}</span>
                {day.theme && <span className="text-base font-bold text-gray-900">{day.theme}</span>}
              </div>

              {day.notes && (
                <p className="text-sm text-amber-700 bg-amber-50 border border-amber-100 rounded-xl px-4 py-3 mb-4 leading-relaxed">
                  {day.notes}
                </p>
              )}

              <div className="space-y-3">
                {day.blocks.map((block) => {
                  const timeStr = block.time
                    ? `${fmt(block.time.start)}${block.time.end ? ` – ${fmt(block.time.end)}` : ""}`
                    : "";
                  const isNote     = block.item.type === "NOTE";
                  const isLogistic = !!block.logisticsType;

                  return (
                    <div key={block.id} className="flex items-start gap-3">
                      {timeStr && (
                        <span className="text-xs text-gray-400 font-mono mt-0.5 w-24 shrink-0">{timeStr}</span>
                      )}
                      <div className={`mt-1.5 h-2 w-2 rounded-full shrink-0 ${
                        isNote     ? "bg-amber-400" :
                        isLogistic ? "bg-blue-400"  :
                                     "bg-primary"
                      }`} />
                      <div>
                        <p className={`text-sm font-semibold ${isNote ? "text-amber-700" : "text-gray-900"}`}>
                          {block.customTitle ?? block.item.name}
                        </p>
                        {block.item.location && (
                          <p className="text-xs text-gray-400 mt-0.5">{block.item.location}</p>
                        )}
                        {block.guideNote && (
                          <p className="text-xs text-gray-500 mt-1 italic">{block.guideNote}</p>
                        )}
                        {block.item.price > 0 && (
                          <p className="text-xs text-gray-400 mt-0.5">
                            TND {block.item.price}
                            {block.item.priceLabel ? ` / ${block.item.priceLabel}` : ""}
                          </p>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>
          ))}

          <p className="text-center text-xs text-gray-400 mt-8">
            guidni.com · {new Date().toLocaleDateString(locale)}
          </p>
        </div>
      </div>
    </>
  );
}
